//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBetter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyBetter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string EntryExerciseHeader {
            get {
                return ResourceManager.GetString("EntryExerciseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise you&apos;ve done today.
        /// </summary>
        public static string EntryExerciseInstructions {
            get {
                return ResourceManager.GetString("EntryExerciseInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x Gratitudes.
        /// </summary>
        public static string EntryGratitudeHeader {
            get {
                return ResourceManager.GetString("EntryGratitudeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three new things you&apos;re grateful for.
        /// </summary>
        public static string EntryGratitudeInstructions {
            get {
                return ResourceManager.GetString("EntryGratitudeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string EntryJournalHeader {
            get {
                return ResourceManager.GetString("EntryJournalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive experience you&apos;ve had.
        /// </summary>
        public static string EntryJournalInstructions {
            get {
                return ResourceManager.GetString("EntryJournalInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditation.
        /// </summary>
        public static string EntryMeditationHeader {
            get {
                return ResourceManager.GetString("EntryMeditationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A couple minutes of relaxation.
        /// </summary>
        public static string EntryMeditationInstructions {
            get {
                return ResourceManager.GetString("EntryMeditationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Act of Kindness.
        /// </summary>
        public static string EntryRAOKHeader {
            get {
                return ResourceManager.GetString("EntryRAOKHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happy for someone else.
        /// </summary>
        public static string EntryRAOKInstructions {
            get {
                return ResourceManager.GetString("EntryRAOKInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This App.
        /// </summary>
        public static string MainAboutHeader {
            get {
                return ResourceManager.GetString("MainAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string MainDatesHeader {
            get {
                return ResourceManager.GetString("MainDatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string MainHowHeader {
            get {
                return ResourceManager.GetString("MainHowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MainStatusHeader {
            get {
                return ResourceManager.GetString("MainStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done For Today.
        /// </summary>
        public static string MainStatusHeaderDoneForToday {
            get {
                return ResourceManager.GetString("MainStatusHeaderDoneForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Entries.
        /// </summary>
        public static string MainStatusHeaderNumberOfCompletedEntries {
            get {
                return ResourceManager.GetString("MainStatusHeaderNumberOfCompletedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Days Completed.
        /// </summary>
        public static string MainStatusHeaderNumberOfConsecutiveCompletedEntries {
            get {
                return ResourceManager.GetString("MainStatusHeaderNumberOfConsecutiveCompletedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Days with Entries.
        /// </summary>
        public static string MainStatusHeaderNumberOfConsecutiveEntries {
            get {
                return ResourceManager.GetString("MainStatusHeaderNumberOfConsecutiveEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string MainStatusHeaderNumberOfEntries {
            get {
                return ResourceManager.GetString("MainStatusHeaderNumberOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string MainTitleBegin {
            get {
                return ResourceManager.GetString("MainTitleBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string MainTitleEnd {
            get {
                return ResourceManager.GetString("MainTitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What To Do.
        /// </summary>
        public static string MainWhatHeader {
            get {
                return ResourceManager.GetString("MainWhatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
