//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBetter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyBetter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be a better, happier you!.
        /// </summary>
        public static string AboutConclusion {
            get {
                return ResourceManager.GetString("AboutConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no affiliation with TED or Shawn Achor..
        /// </summary>
        public static string AboutDisclaimer {
            get {
                return ResourceManager.GetString("AboutDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is based off of Shawn Achor&apos;s TEDx Talk, &quot;The happy secret to better work&quot;, which you can find right below..
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Acts of Kindness.
        /// </summary>
        public static string ActivityFive {
            get {
                return ResourceManager.GetString("ActivityFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write an email or directly praise or thank one person in your social support network..
        /// </summary>
        public static string ActivityFiveDescription {
            get {
                return ResourceManager.GetString("ActivityFiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditation.
        /// </summary>
        public static string ActivityFour {
            get {
                return ResourceManager.GetString("ActivityFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditation allows your brain to get over the cultural ADHD that we&apos;ve been creating by doing multiple things at once..
        /// </summary>
        public static string ActivityFourDescription {
            get {
                return ResourceManager.GetString("ActivityFourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the 5 activities identified in creating lasting, positive change. Done for 21 days in a row, you can train your brain to reverse the formula for happiness and success, and create ripples of positivity..
        /// </summary>
        public static string ActivityIntroduction {
            get {
                return ResourceManager.GetString("ActivityIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Gratitudes.
        /// </summary>
        public static string ActivityOne {
            get {
                return ResourceManager.GetString("ActivityOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down 3 new things you are grateful for..
        /// </summary>
        public static string ActivityOneDescription {
            get {
                return ResourceManager.GetString("ActivityOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string ActivityThree {
            get {
                return ResourceManager.GetString("ActivityThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise teaches your brain that your behavior matters..
        /// </summary>
        public static string ActivityThreeDescription {
            get {
                return ResourceManager.GetString("ActivityThreeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journaling.
        /// </summary>
        public static string ActivityTwo {
            get {
                return ResourceManager.GetString("ActivityTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalling about one positive you&apos;ve had over the past 24 hours allows you to relive it..
        /// </summary>
        public static string ActivityTwoDescription {
            get {
                return ResourceManager.GetString("ActivityTwoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
